//STAROILD
export const GET_MARKET_STAROILD_LOADING = 'GET_MARKET_STAROILD_LOADING'; 
export const GET_MARKET_STAROILD_LOADED = 'GET_MARKET_STAROILD_LOADED';
export const GET_MARKET_STAROILD_FAIL_ACTION = 'GET_MARKET_STAROILD_FAIL_ACTION';
//WORKSHOPS
export const GET_MARKET_WORKSHOPS_LOADING = 'GET_MARKET_WORKSHOPS_LOADING'; 
export const GET_MARKET_WORKSHOPS_LOADED = 'GET_MARKET_WORKSHOPS_LOADED';
export const GET_MARKET_WORKSHOPS_FAIL_ACTION = 'GET_MARKET_WORKSHOPS_FAIL_ACTION';
//RESTAURANT
export const GET_MARKET_RESTAURANT_LOADING = 'GET_MARKET_RESTAURANT_LOADING'; 
export const GET_MARKET_RESTAURANT_LOADED = 'GET_MARKET_RESTAURANT_LOADED';
export const GET_MARKET_RESTAURANT_FAIL_ACTION = 'GET_MARKET_RESTAURANT_FAIL_ACTION';
//HOTEL
export const GET_MARKET_HOTEL_LOADING = 'GET_MARKET_HOTEL_LOADING'; 
export const GET_MARKET_HOTEL_LOADED = 'GET_MARKET_HOTEL_LOADED';
export const GET_MARKET_HOTEL_FAIL_ACTION = 'GET_MARKET_HOTEL_FAIL_ACTION';


/*
GET_MARKET_STAROILD_LOADING, 
GET_MARKET_STAROILD_LOADED,
GET_MARKET_STAROILD_FAIL_ACTION,
GET_MARKET_WORKSHOPS_LOADING, 
GET_MARKET_WORKSHOPS_LOADED,
GET_MARKET_WORKSHOPS_FAIL_ACTION,
GET_MARKET_RESTAURANT_LOADING, 
GET_MARKET_RESTAURANT_LOADED,
GET_MARKET_RESTAURANT_FAIL_ACTION,
GET_MARKET_HOTEL_LOADING, 
GET_MARKET_HOTEL_LOADED,
GET_MARKET_HOTEL_FAIL_ACTION,
*/