// REGION SPAIN
export const GET_REGION_SPAIN_LOADING = 'GET_REGION_SPAIN_LOADING'; 
export const GET_REGION_SPAIN_LOADED = 'GET_REGION_SPAIN_LOADED';
export const GET_REGION_SPAIN_FAIL_ACTION = 'GET_REGION_SPAIN_FAIL_ACTION';