export const GET_APP_SETTINGS_LOADING = 'GET_APP_SETTINGS_LOADING';
export const GET_APP_SETTINGS_LOADED = 'GET_APP_SETTINGS_LOADED';
export const GET_APP_SETTINGS_FAIL = 'GET_APP_SETTINGS_FAIL';

export const EMMIT_ERROR = 'EMMIT_ERROR';
export const HIDE_ERROR_MESSAGE = 'HIDE_ERROR_MESSAGE';
export const EMMIT_CRITICAL_ERROR = 'EMMIT_CRITICAL_ERROR';